version: '3.6'
services:
  dejavu:
    command: tail -f /dev/null
    build:
      context: .
      args:
        - PYTHON_VERSION
    environment:
      - DATABASE_URL=postgres://dejavu:dejavu@database/dejavu
    links:
      - database:db 
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=dejavu
      - POSTGRES_PASSWORD=dejavu
    ports:
      - "5432"
